<a href="https://colab.research.google.com/github/detleffolke/PyTorch-for-Deep-Learning-and-Computer-Vision-Course-All-Codes-/blob/master/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
from torch.nn import Linear

In [2]:
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

In [4]:
def forward(x):
  y = w*x + b
  return y

In [8]:
x = torch.tensor([[2], [7]])
forward(x)

tensor([[ 7.],
        [22.]], grad_fn=<AddBackward0>)

In [11]:
torch.manual_seed(1)
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [15]:
x = torch.tensor([[2.0],[4.0]])
model(x)

tensor([[0.5891],
        [1.6197]], grad_fn=<AddmmBackward>)